### ISSUE TITLE
Crash in __memmove_avx_unaligned_erms

### ISSUE THREAD

**Issue by bdaase** [fenrus75/powertop#93]
* Fedora 35
* powertop 2.14

When running `sudo powertop --html=powerreport.html`, powertop crashes. The trace looks as follows

```
(gdb) bt full
#0  0x00007ffff7b63a3b in __memmove_avx_unaligned_erms () from /lib64/libc.so.6
No symbol table info available.
#1  0x0000555555576bbf in std::char_traits<char>::copy (__n=<optimized out>, __s2=0x7fffffffab00 "C1", __s1=<optimized out>) at /usr/include/c++/11/bits/char_traits.h:409
No locals.
#2  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy (__n=<optimized out>, __s=0x7fffffffab00 "C1", __d=<optimized out>) at /usr/include/c++/11/bits/basic_string.h:359
No locals.
#3  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy (__n=<optimized out>, __s=0x7fffffffab00 "C1", __d=<optimized out>) at /usr/include/c++/11/bits/basic_string.h:354
No locals.
#4  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator= (__str=..., this=0x555555af7de8) at /usr/include/c++/11/bits/basic_string.h:739
No locals.
#5  report_display_cpu_cstates () at cpu/cpu.cpp:580
        first_cpu = true
        first_core = false
        num_cpus = <optimized out>
        num_cores = <optimized out>
        pkg_data = 0x555555607f98
        core_data = <optimized out>
        cpu_data = <optimized out>
        buffer = "C1\000\060,0 ms\000\247\367\377\177\000\000\200\005\000\000\000\000\000\000\200\355\033WUU\000\000\300\257\377\377\377\177\000\000\310v\257UUU\000\000\220\260\377\377\377\177\000\000M\271YUUU\000\000\002\000\000\000\000\000\000\000h{\257UUU\000\000\200\355\033WUU\000\000\340\257\377\377\377\177\000\000\v\000\000\000\000\000\000\000\210\355\033WUU\000\000@\257\377\377\377\177\000\000Я\377\377\377\177\000\000\060\000\000\000\000\000\000\000\350u\257UUU\000\000\340u\257UUU\000\000\060\000\000\000\000\000\000\000\364\003[UUU\000\000!\024[UUU\000\000\020\b[UUU\000\000x6[UUU\000\000\331\003[UUU\000\000!"...
        buffer2 = "\000 0,0%\000\000@\255\377\377\377\177\000\000P\371]UUU\000\000Nѡ\367\377\177\000\000\230ؽ\367\377\177\000\000\370\255\377\377\377\177\000\000 \371]UUU\000\000\000\000\000\000\001", '\000' <repeats 11 times>, "`\255\377\377\377\177\000\000\200\375]UUU\000\000a6[UUU\000\000\026\000\000\000\000\000\000\000\026\000\000\000UU\000\000P\000\000\000\377\177\000\000>\000\000\000UU\000\000\377\377\377\377\377\377\377\377", '\000' <repeats 16 times>, "\n\000\000\000\000\000\000\000\377\377\377\377\377\177\000\000\000?0\262\224\t\022t\020\256\377\377\377\177\000\000\370\255\377\377\377\177\000\000 \371]UUU\000\000p\374"...
        tmp_num = "13\000e 6\000\000\230ؽ\367\377\177", '\000' <repeats 14 times>, "\377\177\000\000\000\375]UUU\000\000\220\257\377\377\000\000\000\000\220\257"
        package = 0
        core = 6
        cpu = <optimized out>
        line = 1
        cstates_num = 3
        title = 25
        core_num = 7
        _package = 0x5555555e1ce0
        _core = 0x5555555e3600
        _cpu = <optimized out>
        core_type = <optimized out>
        div_attr = {css_class = 0x5555555b0810 "clear_block", css_id = 0x5555555b12e4 "cpuidle"}
        std_table_css = {table_class = 0x7ffff7bdbaa0 <main_arena> "", td_class = 0xc <error: Cannot access memory at address 0xc>, tr_class = 0xe0 <error: Cannot access memory at address 0xe0>, 
          th_class = 0x7 <error: Cannot access memory at address 0x7>, pos_table_title = 208, title_mod = 0, rows = 1662457502, cols = 1145428308}
        pkg_tbl_size = {rows = 7, cols = 2}
        core_tbl_size = {rows = 32, cols = 2}
        cpu_tbl_size = {rows = 56, cols = 5}
        title_attr = {css_class = 0x5555555b03f4 "content_title", css_id = 0x5555555b1421 ""}
        idx1 = 10
        idx2 = 64
        idx3 = 160
        tmp_str = "C1"
#6  0x000055555556fc8a in one_measurement (seconds=<optimized out>, sample_interval=<optimized out>, workload=<optimized out>) at /usr/src/debug/powertop-2.14-2.fc35.x86_64/src/main.cpp:265
No locals.
#7  0x0000555555564bce in make_report (file=0x7fffffffc370 "powerreport.html", sample_interval=5, iterations=1, workload=0x7fffffffb370 "", time=20) at /usr/src/debug/powertop-2.14-2.fc35.x86_64/src/main.cpp:300
No locals.
#8  main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/powertop-2.14-2.fc35.x86_64/src/main.cpp:521
        option_index = 5
        c = <optimized out>
        filename = "powerreport.html", '\000' <repeats 2744 times>...
        workload = '\000' <repeats 4095 times>
        iterations = 1
        auto_tune = 0
        sample_interval = 5
```

**Comment by dirkmueller** [comment]
duplicate of #64 ?
